// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240210160037_InitialSetup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizers",
                            Description = "Ditch the cocktail sauce and serve this classic appetizer with a spicy twist",
                            ImageUrl = "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/10/16/1/tm1b55_shrimp_cocktail_remoulade2.jpg.rend.hgtvcom.791.594.suffix/1400611025252.jpeg",
                            Name = "Shrim Cocktail",
                            Price = 12.9
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Appetizers",
                            Description = "Crab Cakes and 5-Ingredient Remoulade",
                            ImageUrl = "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2022/01/11/0/WU3005_ree-drummond-crab-cakes-and-5-ingredient-remoulade_s4x3.jpg.rend.hgtvcom.791.594.suffix/1641930057492.jpeg",
                            Name = "Crab Cakes",
                            Price = 15.9
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Desserts",
                            Description = "Classic bread pudding is enhanced with coconut flakes and coconut milk.",
                            ImageUrl = "https://www.allrecipes.com/thmb/HF3Ylq-b_VE8_X4NfCdGL7nS3sk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/263143-0041adde94f1489496b5c578686a582f.jpg",
                            Name = "Coconut Bread Pudding",
                            Price = 9.9000000000000004
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Entree",
                            Description = "Crispy fish tacos with shredded cabbage and a spicy homemade white sauce",
                            ImageUrl = "https://www.allrecipes.com/thmb/mNCnzOIxW0A9CtgFRkrRC7qYWLk=/0x512/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/53729-fish-tacos-DDMFS-4x3-b5547c67c6f0432da06ad8f905e82c1e.jpg",
                            Name = "Fish Tacos",
                            Price = 16.899999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
